# Generated by Django 2.0.2 on 2018-02-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='식당 이름')),
                ('addr', models.TextField(blank=True, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='RestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='식당 이미지')),
                ('rest_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Rest')),
            ],
        ),
    ]
