# Generated by Django 2.0.2 on 2018-03-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rest_lnglat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='lnglat',
        ),
    ]
