# Generated by Django 2.0.2 on 2018-03-12 09:43

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_remove_rest_lnglat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도/위도 포맷으로 입력', max_length=50, validators=[rest.models.lnglat_validator], verbose_name='지도 경도,위도'),
        ),
    ]
